@startuml DaySave Use Case Comments
left to right direction
actor User
rectangle Comments {
  ( Add comment )
  User --> ( Add comment )
  ( View comment )
  User --> ( View comment )
  ( Edit comment )
  User --> ( Edit comment )
  ( Delete comment )
  User --> ( Delete comment )
  ( Search comment )
  User --> ( Search comment )
}
@enduml
